import { useState } from 'react';
import { api, type AssignmentListQuery } from '../../api/client';
import { useResource } from '../../api/use-resource';
import { DataTable, EmptyState, ErrorState, Field, LoadingState, PageHeader, Pager, StatusBadge } from '../../components/ui';

export function AssignmentsPage() {
  const catalogs = useResource(() => Promise.all([api.departments(), api.academicYears(), api.academicLevels()]), []);
  const [filters, setFilters] = useState<AssignmentListQuery>({ page: 1, pageSize: 25, status: 'ACTIVE' });
  const resource = useResource(() => api.assignments(filters), [filters]);

  return <>
    <PageHeader eyebrow="SUPERVISOR OPERATIONS" title="تكليفات المشرفين" description="التكليفات والنطاقات والصلاحيات كما أعادها الخادم للحساب الحالي." />
    <section className="surface filter-panel"><div className="filter-row"><Field label="القسم"><select value={filters.departmentId ?? ''} onChange={(event) => setFilters({ ...filters, departmentId: event.target.value || undefined, page: 1 })}><option value="">كل الأقسام</option>{catalogs.data?.[0].map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="السنة"><select value={filters.academicYearId ?? ''} onChange={(event) => setFilters({ ...filters, academicYearId: event.target.value || undefined, page: 1 })}><option value="">كل السنوات</option>{catalogs.data?.[1].map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label="المستوى"><select value={filters.academicLevelId ?? ''} onChange={(event) => setFilters({ ...filters, academicLevelId: event.target.value || undefined, page: 1 })}><option value="">كل المستويات</option>{catalogs.data?.[2].map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label="الحالة"><select value={filters.status ?? ''} onChange={(event) => setFilters({ ...filters, status: (event.target.value || undefined) as AssignmentListQuery['status'], page: 1 })}><option value="">كل الحالات</option><option value="ACTIVE">ACTIVE</option><option value="CLOSED">CLOSED</option><option value="REMOVED">REMOVED</option><option value="ARCHIVED">ARCHIVED</option></select></Field></div></section>
    {catalogs.loading || resource.loading ? <LoadingState /> : catalogs.error ? <ErrorState error={catalogs.error} onRetry={catalogs.reload} /> : resource.error ? <ErrorState error={resource.error} onRetry={resource.reload} /> : !resource.data?.items.length ? <EmptyState title="لا توجد تكليفات" description="لم يعُد الخادم تكليفات مطابقة ضمن النطاق الحالي." /> : <section className="surface"><DataTable><thead><tr><th>المشرف</th><th>السياق</th><th>الفترة</th><th>الصلاحيات</th><th>الحالة</th></tr></thead><tbody>{resource.data.items.map((assignment) => <tr key={assignment.id}><td><b>{assignment.supervisorDisplayName ?? 'حساب مشرف'}</b><small className="block mono">{assignment.supervisorAccountId}</small></td><td><span className="block">{catalogs.data?.[0].find((item) => item.id === assignment.departmentId)?.name ?? assignment.departmentId}</span><small className="block">{catalogs.data?.[2].find((item) => item.id === assignment.academicLevelId)?.label ?? assignment.academicLevelId}{assignment.groupId ? ' · Group scoped' : assignment.cohortId ? ' · Cohort scoped' : ''}</small></td><td>{new Date(assignment.effectiveFrom).toLocaleDateString('ar')}<small className="block">إلى {assignment.effectiveTo ? new Date(assignment.effectiveTo).toLocaleDateString('ar') : 'مفتوح'}</small></td><td><div className="permission-pills"><span className={assignment.permissions.reviewCases ? 'allowed' : 'denied'}>Review</span><span className={assignment.permissions.grade ? 'allowed' : 'denied'}>Grade</span></div></td><td><StatusBadge value={assignment.status} /><small className="block">Revision {assignment.revision}</small></td></tr>)}</tbody></DataTable><Pager {...resource.data.page} onPage={(page) => setFilters({ ...filters, page })} /></section>}
  </>;
}
