import type { FastifySchema } from 'fastify';

const uuid={type:'string',format:'uuid'} as const;
const dateTime={type:'string',format:'date-time'} as const;
const nullableUuid={anyOf:[uuid,{type:'null'}]} as const;
const nullableString={anyOf:[{type:'string'},{type:'null'}]} as const;
const nullableDateTime={anyOf:[dateTime,{type:'null'}]} as const;
const nullableNumber={anyOf:[{type:'number'},{type:'null'}]} as const;
const idempotency={type:'string',minLength:16,maxLength:200,pattern:'^[A-Za-z0-9._-]+$'} as const;
const lifecycle={type:'string',enum:['ACTIVE','CLOSED','REMOVED','ARCHIVED']} as const;
const submissionStatus={type:'string',enum:['DRAFT','SUBMITTED','REVISION_REQUESTED','APPROVED_START','APPROVED_FINAL','GRADED']} as const;
const role={type:'string',enum:['UNIVERSITY_ADMIN','DEPARTMENT_ADMIN','CLINICAL_SUPERVISOR','STUDENT_INTEGRATION']} as const;
const problem={type:'object',required:['error'],additionalProperties:false,properties:{error:{type:'object',required:['code','message','requestId'],additionalProperties:false,properties:{code:{type:'string'},message:{type:'string'},requestId:{type:'string'},details:{type:'object',additionalProperties:{type:'array',items:{type:'string'}}}}}}} as const;
const problems={400:problem,401:problem,403:problem,404:problem,409:problem,429:problem,500:problem};
const idParams={type:'object',required:['id'],additionalProperties:false,properties:{id:uuid}} as const;
const pageQuery={page:{type:'integer',minimum:1,default:1},pageSize:{type:'integer',minimum:1,maximum:100,default:25}} as const;
const pageMeta={type:'object',required:['page','pageSize','total','totalPages'],additionalProperties:false,properties:{page:{type:'integer'},pageSize:{type:'integer'},total:{type:'integer'},totalPages:{type:'integer'}}} as const;
const enrollmentSummary={type:'object',required:['id','academicYearId','academicLevelId','cohortId','status','startedAt','closedAt','closeReason','revision'],additionalProperties:false,properties:{id:uuid,academicYearId:uuid,academicLevelId:uuid,cohortId:uuid,status:{type:'string',enum:['ACTIVE','CLOSED']},startedAt:dateTime,closedAt:nullableDateTime,closeReason:nullableString,revision:{type:'integer'}}} as const;
const studentListItem={type:'object',required:['id','studentNumber','displayName','status','revision','activeEnrollment','departmentIds'],additionalProperties:false,properties:{id:uuid,studentNumber:{type:'string'},displayName:{type:'string'},status:lifecycle,revision:{type:'integer'},activeEnrollment:{anyOf:[enrollmentSummary,{type:'null'}]},departmentIds:{type:'array',items:uuid}}} as const;
const assignment={type:'object',required:['id','supervisorAccountId','supervisorDisplayName','departmentId','academicYearId','academicLevelId','cohortId','groupId','status','effectiveFrom','effectiveTo','revision','reason','permissions'],additionalProperties:false,properties:{id:uuid,supervisorAccountId:uuid,supervisorDisplayName:nullableString,departmentId:uuid,academicYearId:uuid,academicLevelId:uuid,cohortId:nullableUuid,groupId:nullableUuid,status:lifecycle,effectiveFrom:dateTime,effectiveTo:nullableDateTime,revision:{type:'integer'},reason:{type:'string'},permissions:{type:'object',required:['reviewCases','grade'],additionalProperties:false,properties:{reviewCases:{type:'boolean'},grade:{type:'boolean'}}}}} as const;
const submissionListItem={type:'object',required:['id','caseSheetId','studentId','studentNumber','studentDisplayName','departmentId','termId','academicYearId','academicLevelId','cohortId','groupId','supervisorAssignmentId','status','sequence','submittedAt'],additionalProperties:false,properties:{id:uuid,caseSheetId:uuid,studentId:uuid,studentNumber:{type:'string'},studentDisplayName:{type:'string'},departmentId:uuid,termId:uuid,academicYearId:uuid,academicLevelId:uuid,cohortId:uuid,groupId:nullableUuid,supervisorAssignmentId:nullableUuid,status:submissionStatus,sequence:{type:'integer'},submittedAt:dateTime}} as const;
const aggregate={type:'object',required:['organizationId','academicYearId','totalStudents','totalSubmittedCases','pendingClinicalDecisions','generatedAt'],additionalProperties:false,properties:{organizationId:uuid,academicYearId:uuid,totalStudents:{type:'integer'},totalSubmittedCases:{type:'integer'},pendingClinicalDecisions:{type:'integer'},generatedAt:dateTime}} as const;
const reportQuery={type:'object',required:['academicYearId'],additionalProperties:false,properties:{academicYearId:uuid,departmentId:uuid}} as const;
const jsonPayload={type:'object',additionalProperties:true} as const;
const studentDraft={type:'object',required:['id','enrollmentId','termId','templateVersionId','payload','revision','createdAt','updatedAt'],additionalProperties:false,properties:{id:uuid,enrollmentId:uuid,termId:uuid,templateVersionId:uuid,payload:jsonPayload,revision:{type:'integer'},createdAt:dateTime,updatedAt:dateTime}} as const;
const studentSubmissionListItem={type:'object',required:['snapshotId','status','submittedAt'],additionalProperties:false,properties:{snapshotId:uuid,status:submissionStatus,submittedAt:dateTime,studentVisibleFeedback:{type:'string'}}} as const;
const studentDecision={type:'object',required:['type','reason','createdAt'],additionalProperties:false,properties:{type:{type:'string',enum:['APPROVE_START','APPROVE_FINAL','REQUEST_REVISION']},reason:nullableString,createdAt:dateTime}} as const;
const studentFeedbackNote={type:'object',required:['id','body','createdAt'],additionalProperties:false,properties:{id:uuid,body:{type:'string'},createdAt:dateTime}} as const;
const studentGrade={type:'object',required:['grade','maxGrade','comment','createdAt'],additionalProperties:false,properties:{grade:{type:'number'},maxGrade:{type:'number'},comment:{type:'string'},createdAt:dateTime}} as const;
const studentAttachment={type:'object',required:['id','fileId','contentType','byteSize','sha256','createdAt'],additionalProperties:false,properties:{id:uuid,fileId:uuid,contentType:{type:'string'},byteSize:{type:'integer'},sha256:{type:'string'},createdAt:dateTime}} as const;
const supervisorSummary={type:'object',required:['id','active','display_name','email'],additionalProperties:false,properties:{id:uuid,active:{type:'boolean'},display_name:{type:'string'},email:{type:'string',format:'email'}}} as const;
const supervisorGrant={type:'object',required:['id','permission_set_version_id','granted_at','revoked_at','assignment_id','department_id'],additionalProperties:false,properties:{id:uuid,permission_set_version_id:uuid,granted_at:dateTime,revoked_at:nullableDateTime,assignment_id:uuid,department_id:nullableUuid}} as const;
const dutySchedule={type:'object',required:['id','department_id','academic_year_id','timezone','valid_from','valid_to'],additionalProperties:false,properties:{id:uuid,department_id:uuid,academic_year_id:uuid,timezone:{type:'string'},valid_from:dateTime,valid_to:dateTime}} as const;
const dutyShiftMember={type:'object',required:['member_id','assignment_id','supervisor_name'],additionalProperties:false,properties:{member_id:uuid,assignment_id:uuid,supervisor_name:nullableString}} as const;
const dutyShift={type:'object',required:['id','starts_at','ends_at','status','members'],additionalProperties:false,properties:{id:uuid,starts_at:dateTime,ends_at:dateTime,status:lifecycle,members:{anyOf:[{type:'array',items:dutyShiftMember},{type:'null'}]}}} as const;
const supervisorDuty={type:'object',required:['id','starts_at','ends_at','assignment_id'],additionalProperties:false,properties:{id:uuid,starts_at:dateTime,ends_at:dateTime,assignment_id:uuid}} as const;
const supervisorDutyCase={type:'object',required:['snapshot_id','current_status'],additionalProperties:false,properties:{snapshot_id:uuid,current_status:submissionStatus}} as const;
const supervisorCaseDetail={type:'object',required:['snapshot_id','current_status','payload','allowedActions'],additionalProperties:false,properties:{snapshot_id:uuid,current_status:submissionStatus,payload:jsonPayload,allowedActions:{type:'array',items:{type:'string',enum:['START_APPROVAL','COMPLETION_APPROVAL','CASESHEET_EVALUATION','CLINICAL_FEEDBACK']}}}} as const;

const supervisorNextAction={type:'string',enum:['START_APPROVAL','COMPLETION_APPROVAL','EVALUATION','FEEDBACK','NONE']} as const;
const supervisorCapability={type:'string',enum:['DAILY_SHEET_READ','REVIEW_QUEUE_READ','HISTORY_READ','WORK_SUMMARY_READ','START_APPROVAL','COMPLETION_APPROVAL','CASESHEET_EVALUATION','CLINICAL_FEEDBACK']} as const;
const supervisorDailySheetItem={type:'object',required:['snapshot_id','case_sheet_id','student_id','student_number','student_display_name','department_id','department_name','requirement_id','subject_code','subject_name','shift_id','shift_starts_at','shift_ends_at','case_status','start_status','completion_status','evaluation_status','evaluation_score','next_action','allowedActions'],additionalProperties:false,properties:{snapshot_id:uuid,case_sheet_id:uuid,student_id:uuid,student_number:{type:'string'},student_display_name:{type:'string'},department_id:uuid,department_name:{type:'string'},requirement_id:nullableUuid,subject_code:nullableString,subject_name:nullableString,shift_id:uuid,shift_starts_at:dateTime,shift_ends_at:dateTime,case_status:submissionStatus,start_status:{type:'string',enum:['PENDING','APPROVED']},completion_status:{type:'string',enum:['PENDING','APPROVED']},evaluation_status:{type:'string',enum:['PENDING','RECORDED']},evaluation_score:nullableNumber,next_action:supervisorNextAction,allowedActions:{type:'array',items:{type:'string',enum:['START_APPROVAL','COMPLETION_APPROVAL','CASESHEET_EVALUATION','CLINICAL_FEEDBACK']}}}} as const;
const supervisorDailySheet={type:'object',required:['duty','items','generated_at'],additionalProperties:false,properties:{duty:{anyOf:[supervisorDuty,{type:'null'}]},items:{type:'array',items:supervisorDailySheetItem},generated_at:dateTime}} as const;
const supervisorReviewQueueItem={type:'object',required:[...supervisorDailySheetItem.required,'action_required','original_duty_date','is_action_allowed_now'],additionalProperties:false,properties:{...supervisorDailySheetItem.properties,action_required:supervisorNextAction,original_duty_date:{type:'string',format:'date'},is_action_allowed_now:{type:'boolean'}}} as const;
const supervisorReviewQueue={type:'object',required:['items','generated_at'],additionalProperties:false,properties:{items:{type:'array',items:supervisorReviewQueueItem},generated_at:dateTime}} as const;
const supervisorHistoryShift={type:'object',required:['shift_id','starts_at','ends_at','status'],additionalProperties:false,properties:{shift_id:uuid,starts_at:dateTime,ends_at:dateTime,status:lifecycle}} as const;
const supervisorHistoryDayItem={type:'object',required:[...supervisorDailySheetItem.required,'status_at_day_end','performed_actions','remained_pending'],additionalProperties:false,properties:{...supervisorDailySheetItem.properties,status_at_day_end:submissionStatus,performed_actions:{type:'array',items:{type:'string'}},remained_pending:{type:'boolean'}}} as const;
const supervisorHistoryDay={type:'object',required:['date','shifts','items','generated_at'],additionalProperties:false,properties:{date:{type:'string',format:'date'},shifts:{type:'array',items:supervisorHistoryShift},items:{type:'array',items:supervisorHistoryDayItem},generated_at:dateTime}} as const;
const supervisorWorkSummary={type:'object',required:['academic_year_id','term_id','supervision_days','start_approvals','completion_approvals','evaluations','feedback_notes','deferred_work','generated_at'],additionalProperties:false,properties:{academic_year_id:uuid,term_id:nullableUuid,supervision_days:{type:'integer'},start_approvals:{type:'integer'},completion_approvals:{type:'integer'},evaluations:{type:'integer'},feedback_notes:{type:'integer'},deferred_work:{type:'integer'},generated_at:dateTime}} as const;
const supervisorCapabilities={type:'object',required:['capabilities','generated_at'],additionalProperties:false,properties:{capabilities:{type:'array',items:supervisorCapability},generated_at:dateTime}} as const;

export const routeSchemas = {
  live:{summary:'Liveness probe',response:{200:{type:'object',required:['status'],additionalProperties:false,properties:{status:{type:'string',enum:['live']}}}}},
  ready:{summary:'Dependency readiness probe',response:{200:{type:'object',required:['status'],additionalProperties:false,properties:{status:{type:'string',enum:['ready']}}},503:{type:'object',required:['status'],additionalProperties:false,properties:{status:{type:'string',enum:['not_ready']}}}}},
  openapi:{summary:'OpenAPI document',response:{200:{type:'object',required:['openapi','info','paths'],additionalProperties:true,properties:{openapi:{type:'string'},info:{type:'object',additionalProperties:true},paths:{type:'object',additionalProperties:true}}}}},
  login:{summary:'Create a tenant session',body:{type:'object',required:['organizationId','email','password'],additionalProperties:false,properties:{organizationId:uuid,email:{type:'string',format:'email',maxLength:254},password:{type:'string',minLength:12,maxLength:256}}},response:{204:{type:'null'},...problems}},
  logout:{summary:'Revoke the current session',response:{204:{type:'null'},...problems}},
  session:{summary:'Read the current session actor',response:{200:{type:'object',required:['accountId','organizationId','collegeId','role','departmentIds'],additionalProperties:false,properties:{accountId:uuid,organizationId:uuid,collegeId:nullableUuid,role,departmentIds:{type:'array',items:uuid}}},...problems}},
  invitation:{summary:'Issue an invitation',body:{type:'object',required:['email','role'],additionalProperties:false,properties:{email:{type:'string',format:'email'},role,studentId:uuid}},response:{201:{type:'object',additionalProperties:false,properties:{invitationToken:{type:'string'}}},...problems}},
  redeem:{summary:'Redeem an invitation once',body:{type:'object',required:['organizationId','token','password'],additionalProperties:false,properties:{organizationId:uuid,token:{type:'string',minLength:40},password:{type:'string',minLength:12,maxLength:256}}},response:{204:{type:'null'},...problems}},
  departments:{summary:'List departments in the actor scope',response:{200:{type:'array',items:{type:'object',required:['id','collegeId','code','name','active','revision'],additionalProperties:false,properties:{id:uuid,collegeId:uuid,code:{type:'string'},name:{type:'string'},active:{type:'boolean'},revision:{type:'integer'}}}},...problems}},
  academicYears:{summary:'List academic years',response:{200:{type:'array',items:{type:'object',required:['id','label','startsOn','endsOn','status','revision'],additionalProperties:false,properties:{id:uuid,label:{type:'string'},startsOn:{type:'string',format:'date'},endsOn:{type:'string',format:'date'},status:lifecycle,revision:{type:'integer'}}}},...problems}},
  academicLevels:{summary:'List academic levels',response:{200:{type:'array',items:{type:'object',required:['id','code','label','ordinal','active'],additionalProperties:false,properties:{id:uuid,code:{type:'string'},label:{type:'string'},ordinal:{type:'integer'},active:{type:'boolean'}}}},...problems}},
  cohorts:{summary:'List academic cohorts',response:{200:{type:'array',items:{type:'object',required:['id','label','active'],additionalProperties:false,properties:{id:uuid,label:{type:'string'},active:{type:'boolean'}}}},...problems}},
  groups:{summary:'List academic groups in the actor scope',querystring:{type:'object',additionalProperties:false,properties:{departmentId:uuid,academicYearId:uuid,academicLevelId:uuid}},response:{200:{type:'array',items:{type:'object',required:['id','departmentId','academicYearId','academicLevelId','name','rangeStart','rangeEnd','status','revision'],additionalProperties:false,properties:{id:uuid,departmentId:uuid,academicYearId:uuid,academicLevelId:uuid,name:{type:'string'},rangeStart:nullableNumber,rangeEnd:nullableNumber,status:lifecycle,revision:{type:'integer'}}}},...problems}},
  students:{summary:'List students in the actor scope',querystring:{type:'object',additionalProperties:false,properties:{departmentId:uuid,academicYearId:uuid,academicLevelId:uuid,cohortId:uuid,q:{type:'string',minLength:1,maxLength:200},...pageQuery}},response:{200:{type:'object',required:['items','page'],additionalProperties:false,properties:{items:{type:'array',items:studentListItem},page:pageMeta}},...problems}},
  studentDetail:{summary:'Read a student in the actor scope',params:idParams,response:{200:{type:'object',required:['id','collegeId','studentNumber','displayName','status','revision','enrollments'],additionalProperties:false,properties:{id:uuid,collegeId:uuid,studentNumber:{type:'string'},displayName:{type:'string'},status:lifecycle,revision:{type:'integer'},enrollments:{type:'array',items:{...enrollmentSummary,required:[...enrollmentSummary.required,'rosterMemberships','groupMemberships'],properties:{...enrollmentSummary.properties,rosterMemberships:{type:'array',items:{type:'object',required:['id','rosterId','departmentId','status','addedAt','closedAt','reason'],additionalProperties:false,properties:{id:uuid,rosterId:uuid,departmentId:uuid,status:lifecycle,addedAt:dateTime,closedAt:nullableDateTime,reason:nullableString}}},groupMemberships:{type:'array',items:{type:'object',required:['id','groupId','departmentId','status','assignedAt','removedAt','reason'],additionalProperties:false,properties:{id:uuid,groupId:uuid,departmentId:uuid,status:lifecycle,assignedAt:dateTime,removedAt:nullableDateTime,reason:nullableString}}}}}}}},...problems}},
  assignments:{summary:'List supervisor assignments in the actor scope',querystring:{type:'object',additionalProperties:false,properties:{departmentId:uuid,academicYearId:uuid,academicLevelId:uuid,status:lifecycle,...pageQuery}},response:{200:{type:'object',required:['items','page'],additionalProperties:false,properties:{items:{type:'array',items:assignment},page:pageMeta}},...problems}},
  closeEnrollment:{summary:'Close an enrollment atomically',params:idParams,body:{type:'object',required:['expectedRevision','reason','idempotencyKey'],additionalProperties:false,properties:{expectedRevision:{type:'integer',minimum:1},reason:{type:'string',minLength:3,maxLength:500},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  groupMembership:{summary:'Assign or move a group membership',body:{type:'object',required:['groupId','enrollmentId','departmentId','studentId','idempotencyKey'],additionalProperties:false,properties:{groupId:uuid,enrollmentId:uuid,departmentId:uuid,studentId:uuid,idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  submit:{summary:'Submit a student draft as an immutable snapshot',body:{type:'object',required:['draftId','idempotencyKey'],additionalProperties:false,properties:{draftId:uuid,idempotencyKey:idempotency}},response:{201:{type:'object',required:['snapshotId'],additionalProperties:false,properties:{snapshotId:uuid}},...problems}},
  staffSubmissions:{summary:'List submitted cases in the actor scope',querystring:{type:'object',additionalProperties:false,properties:{departmentId:uuid,academicYearId:uuid,academicLevelId:uuid,cohortId:uuid,groupId:uuid,status:submissionStatus,...pageQuery}},response:{200:{type:'object',required:['items','page'],additionalProperties:false,properties:{items:{type:'array',items:submissionListItem},page:pageMeta}},...problems}},
  staffSubmission:{summary:'Read a submitted case in staff scope',params:idParams,response:{200:{...submissionListItem,required:[...submissionListItem.required,'enrollmentId','workflowPolicyVersionId','requirementSetVersionId','requirementId','templateVersionId','gradingPolicyVersionId','payload','revisions','decisions','grades','supervisorNotes','attachments'],properties:{...submissionListItem.properties,enrollmentId:uuid,workflowPolicyVersionId:uuid,requirementSetVersionId:uuid,requirementId:nullableUuid,templateVersionId:uuid,gradingPolicyVersionId:nullableUuid,payload:{type:'object',additionalProperties:true},revisions:{type:'array',items:{type:'object',required:['id','requestedByAccountId','reason','createdAt'],additionalProperties:false,properties:{id:uuid,requestedByAccountId:uuid,reason:{type:'string'},createdAt:dateTime}}},decisions:{type:'array',items:{type:'object',required:['id','type','decidedByAccountId','reason','createdAt'],additionalProperties:false,properties:{id:uuid,type:{type:'string',enum:['APPROVE_START','APPROVE_FINAL','REQUEST_REVISION']},decidedByAccountId:uuid,reason:nullableString,createdAt:dateTime}}},grades:{type:'array',items:{type:'object',required:['id','action','previousGrade','newGrade','maxGrade','reason','comment','createdAt'],additionalProperties:false,properties:{id:uuid,action:{type:'string',enum:['RECORDED','AMENDED']},previousGrade:nullableNumber,newGrade:{type:'number'},maxGrade:{type:'number'},reason:nullableString,comment:{type:'string'},createdAt:dateTime}}},supervisorNotes:{type:'array',items:{type:'object',required:['id','authorAccountId','body','studentVisible','createdAt'],additionalProperties:false,properties:{id:uuid,authorAccountId:uuid,body:{type:'string'},studentVisible:{type:'boolean'},createdAt:dateTime}}},attachments:{type:'array',items:{type:'object',required:['id','fileId','contentType','byteSize','sha256','createdAt'],additionalProperties:false,properties:{id:uuid,fileId:uuid,contentType:{type:'string'},byteSize:{type:'integer'},sha256:{type:'string'},createdAt:dateTime}}}}},...problems}},
  revision:{summary:'Request revision of a submitted case',params:idParams,body:{type:'object',required:['reason','idempotencyKey'],additionalProperties:false,properties:{reason:{type:'string',minLength:3,maxLength:1000},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  approval:{summary:'Apply an authorized clinical approval transition',params:idParams,body:{type:'object',required:['idempotencyKey'],additionalProperties:false,properties:{idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  grade:{summary:'Record or amend a grade',params:idParams,body:{type:'object',required:['grade','comment','idempotencyKey'],additionalProperties:false,properties:{grade:{type:'number',minimum:0,maximum:100},comment:{type:'string',minLength:1,maxLength:2000},reason:{type:'string',maxLength:1000},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  termResult:{summary:'Transition a term result with optimistic concurrency',params:idParams,body:{type:'object',required:['expectedRevision','idempotencyKey'],additionalProperties:false,properties:{expectedRevision:{type:'integer',minimum:1},reason:{type:'string',maxLength:1000},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  aggregate:{summary:'Read aggregate-only academic reporting',querystring:{type:'object',required:['academicYearId'],additionalProperties:false,properties:{academicYearId:uuid}},response:{200:aggregate,...problems}},
  dashboard:{summary:'Read dashboard aggregates in the actor scope',querystring:reportQuery,response:{200:{...aggregate,required:[...aggregate.required,'departmentId','gradedCases','activeSupervisors'],properties:{...aggregate.properties,departmentId:nullableUuid,gradedCases:{type:'integer'},activeSupervisors:{type:'integer'}}},...problems}},
  scopedReport:{summary:'Read department aggregate rows in the actor scope',querystring:reportQuery,response:{200:{type:'object',required:['organizationId','academicYearId','departmentId','rows','generatedAt'],additionalProperties:false,properties:{organizationId:uuid,academicYearId:uuid,departmentId:nullableUuid,rows:{type:'array',items:{type:'object',required:['departmentId','departmentCode','departmentName','studentCount','submittedCases','pendingClinicalDecisions','gradedCases','averageGrade'],additionalProperties:false,properties:{departmentId:uuid,departmentCode:{type:'string'},departmentName:{type:'string'},studentCount:{type:'integer'},submittedCases:{type:'integer'},pendingClinicalDecisions:{type:'integer'},gradedCases:{type:'integer'},averageGrade:nullableNumber}}},generatedAt:dateTime}},...problems}},
  upload:{summary:'Create a private file record and signed upload',body:{type:'object',required:['contentType','byteSize','sha256','idempotencyKey'],additionalProperties:false,properties:{contentType:{type:'string',enum:['application/pdf','image/jpeg','image/png','image/webp']},byteSize:{type:'integer',minimum:1,maximum:26214400},sha256:{type:'string',pattern:'^[a-fA-F0-9]{64}$'},idempotencyKey:idempotency}},response:{201:{type:'object',required:['fileId','uploadUrl','expiresInSeconds','requiredHeaders'],additionalProperties:false,properties:{fileId:uuid,uploadUrl:{type:'string',format:'uri'},expiresInSeconds:{type:'integer'},requiredHeaders:{type:'object',additionalProperties:{type:'string'}}}},...problems}},
  completeUpload:{summary:'Verify and complete an uploaded private file',params:idParams,body:{type:'object',required:['idempotencyKey'],additionalProperties:false,properties:{idempotencyKey:idempotency}},response:{200:{type:'object',required:['fileId','status','completedAt'],additionalProperties:false,properties:{fileId:uuid,status:{type:'string',enum:['UPLOADED','LINKED']},completedAt:dateTime}},...problems}},
  linkAttachment:{summary:'Link a completed upload to an owned student draft',params:idParams,body:{type:'object',required:['draftId','idempotencyKey'],additionalProperties:false,properties:{draftId:uuid,idempotencyKey:idempotency}},response:{201:{type:'object',required:['attachmentId','fileId','draftId'],additionalProperties:false,properties:{attachmentId:uuid,fileId:uuid,draftId:uuid}},...problems}},
  read:{summary:'Create an authorized signed read URL',params:idParams,response:{200:{type:'object',required:['readUrl','expiresInSeconds'],additionalProperties:false,properties:{readUrl:{type:'string',format:'uri'},expiresInSeconds:{type:'integer'}}},...problems}},
  studentDraftCreate:{summary:'Create a draft owned by the current student',body:{type:'object',required:['enrollmentId','templateVersionId','payload','idempotencyKey'],additionalProperties:false,properties:{enrollmentId:uuid,templateVersionId:uuid,payload:jsonPayload,idempotencyKey:idempotency}},response:{201:studentDraft,...problems}},
  studentDrafts:{summary:'List drafts owned by the current student',response:{200:{type:'object',required:['items'],additionalProperties:false,properties:{items:{type:'array',items:studentDraft}}},...problems}},
  studentDraftDetail:{summary:'Read a draft owned by the current student',params:idParams,response:{200:studentDraft,...problems}},
  studentDraftUpdate:{summary:'Update a draft owned by the current student with optimistic concurrency',params:idParams,body:{type:'object',required:['payload','expectedRevision','idempotencyKey'],additionalProperties:false,properties:{payload:jsonPayload,expectedRevision:{type:'integer',minimum:1},idempotencyKey:idempotency}},response:{200:studentDraft,...problems}},
  studentSubmissions:{summary:'List submissions owned by the current student',querystring:{type:'object',additionalProperties:false,properties:{...pageQuery}},response:{200:{type:'object',required:['items','page'],additionalProperties:false,properties:{items:{type:'array',items:studentSubmissionListItem},page:pageMeta}},...problems}},
  studentSubmissionDetail:{summary:'Read a submission owned by the current student',params:idParams,response:{200:{type:'object',required:['snapshotId','caseSheetId','status','sequence','submittedAt','payload','decisions','feedback','grade','attachments'],additionalProperties:false,properties:{snapshotId:uuid,caseSheetId:uuid,status:submissionStatus,sequence:{type:'integer'},submittedAt:dateTime,payload:jsonPayload,decisions:{type:'array',items:studentDecision},feedback:{type:'array',items:studentFeedbackNote},grade:{anyOf:[studentGrade,{type:'null'}]},attachments:{type:'array',items:studentAttachment}}},...problems}},
  listSupervisors:{summary:'List supervisors',response:{200:{type:'object',required:['items'],additionalProperties:false,properties:{items:{type:'array',items:supervisorSummary}}},...problems}},
  supervisorDetail:{summary:'Get supervisor details',params:idParams,response:{200:supervisorSummary,...problems}},
  supervisorGrants:{summary:'List supervisor permission grants',params:idParams,response:{200:{type:'object',required:['items'],additionalProperties:false,properties:{items:{type:'array',items:supervisorGrant}}},...problems}},
  reissueInvitation:{summary:'Reissue a pending supervisor invitation',params:idParams,body:{type:'object',required:['idempotencyKey'],additionalProperties:false,properties:{idempotencyKey:idempotency}},response:{201:{type:'object',additionalProperties:true},...problems}},
  revokeInvitation:{summary:'Revoke a pending supervisor invitation',params:idParams,body:{type:'object',required:['idempotencyKey'],additionalProperties:false,properties:{idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  setSupervisorStatus:{summary:'Disable or reactivate a supervisor account',params:idParams,body:{type:'object',required:['active','idempotencyKey'],additionalProperties:false,properties:{active:{type:'boolean'},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  grantPermission:{summary:'Grant a permission set to an assignment',params:idParams,body:{type:'object',required:['permissionSetVersionId','idempotencyKey'],additionalProperties:false,properties:{permissionSetVersionId:uuid,idempotencyKey:idempotency}},response:{201:{type:'object',required:['id'],additionalProperties:false,properties:{id:uuid}},...problems}},
  revokePermission:{summary:'Revoke an active permission grant',params:idParams,body:{type:'object',required:['idempotencyKey'],additionalProperties:false,properties:{idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  createSchedule:{summary:'Create a clinical duty schedule',body:{type:'object',required:['departmentId','academicYearId','timezone','validFrom','validTo','idempotencyKey'],additionalProperties:false,properties:{departmentId:uuid,academicYearId:uuid,timezone:{type:'string'},validFrom:dateTime,validTo:dateTime,idempotencyKey:idempotency}},response:{201:{type:'object',required:['id'],additionalProperties:false,properties:{id:uuid}},...problems}},
  createShift:{summary:'Create a clinical duty shift',params:idParams,body:{type:'object',required:['startsAt','endsAt','idempotencyKey'],additionalProperties:false,properties:{startsAt:dateTime,endsAt:dateTime,idempotencyKey:idempotency}},response:{201:{type:'object',required:['id'],additionalProperties:false,properties:{id:uuid}},...problems}},
  addShiftMember:{summary:'Add a supervisor assignment to a shift',params:idParams,body:{type:'object',required:['assignmentId','grantId','idempotencyKey'],additionalProperties:false,properties:{assignmentId:uuid,grantId:uuid,idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  listSchedules:{summary:'List clinical duty schedules',response:{200:{type:'object',required:['items'],additionalProperties:false,properties:{items:{type:'array',items:dutySchedule}}},...problems}},
  scheduleDetail:{summary:'Get schedule details and shifts',params:idParams,response:{200:{...dutySchedule,required:[...dutySchedule.required,'shifts'],properties:{...dutySchedule.properties,shifts:{type:'array',items:dutyShift}}},...problems}},
  activeDuty:{summary:'Get active duty for supervisor',response:{200:{type:'array',items:supervisorDuty},...problems}},
  upcomingDuties:{summary:'Get upcoming duties for supervisor',response:{200:{type:'array',items:supervisorDuty},...problems}},
  dutyCases:{summary:'List active cases matching current duty scope',response:{200:{type:'array',items:supervisorDutyCase},...problems}},
  supervisorDailySheet:{summary:'Read the current supervisor daily sheet',response:{200:supervisorDailySheet,...problems}},
  supervisorReviewQueue:{summary:'Read current and deferred supervisor review work',response:{200:supervisorReviewQueue,...problems}},
  supervisorHistoryDay:{summary:'Read a supervisor history day',querystring:{type:'object',required:['date'],additionalProperties:false,properties:{date:{type:'string',format:'date'}}},response:{200:supervisorHistoryDay,...problems}},
  supervisorWorkSummary:{summary:'Read the supervisor work summary',querystring:{type:'object',required:['academicYearId'],additionalProperties:false,properties:{academicYearId:uuid,termId:uuid}},response:{200:supervisorWorkSummary,...problems}},
  supervisorCapabilities:{summary:'Read explicit supervisor capabilities',response:{200:supervisorCapabilities,...problems}},
  supervisorCaseDetail:{summary:'Get case details under active duty',params:idParams,response:{200:supervisorCaseDetail,...problems}},
  supervisorStartApproval:{summary:'Supervisor start approval',params:idParams,body:{type:'object',required:['idempotencyKey'],additionalProperties:false,properties:{idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  supervisorCompletionApproval:{summary:'Supervisor completion approval',params:idParams,body:{type:'object',required:['idempotencyKey'],additionalProperties:false,properties:{idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  supervisorEvaluate:{summary:'Supervisor case evaluation',params:idParams,body:{type:'object',required:['score','idempotencyKey'],additionalProperties:false,properties:{score:{type:'number',minimum:0,maximum:10},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  supervisorFeedback:{summary:'Supervisor clinical feedback',params:idParams,body:{type:'object',required:['body','studentVisible','idempotencyKey'],additionalProperties:false,properties:{body:{type:'string'},studentVisible:{type:'boolean'},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
} satisfies Record<string,FastifySchema>;
